pipeline {
    agent any
     stages {
       
       stage('build') {
          steps {                                
             
            
          }
       }
    
stage('Gradle') {
    steps {
   echo "Gradle..."
        sh 'source /etc/profile.d/gradle.sh'
        sh 'gradle -v'
   
    }
        }
    }
    post { 
        always { 
           
             echo 'DONE!'
        }
    }
}
