pipeline {
    agent any
     stages {
       
       
stage('Gradle') {
    steps {
   echo "Gradle..."
       sh './gradlew clean build'
        
    }
        }
    }
    post { 
        always { 
           
             echo 'DONE!'
        }
    }
}
